name: Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: |
        cmake -S . -B build64 -G "Visual Studio 17 2022" -A x64
        cmake -S . -B build32 -G "Visual Studio 17 2022" -A Win32

    - name: Build
      run: |
        cmake --build build64 --config Release
        cmake --build build32 --config Release

    - name: Add text files
      run: |
        copy COPYING build32/eternity/Release/COPYING.txt
        copy COPYING-EE build32/eternity/Release/COPYING-EE.txt
        copy docs/readme.txt "build32/eternity/Release/ee-$(git describe --tags).txt"

        copy COPYING build64/eternity/Release/COPYING.txt
        copy COPYING-EE build64/eternity/Release/COPYING-EE.txt
        copy docs/readme.txt "build64/eternity/Release/ee-$(git describe --tags).txt"

    - name: Archive release build
      uses: actions/upload-artifact@v4
      with:
        name: windows-release
        path: build??/eternity/Release
